version: '3'
services:
  openai-cache-proxy:
    image: nginx:1.23.4
    container_name: openai-cache-proxy
    #ports:
    #  - 127.0.0.1:81:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./server_cache:/server_cache:rw
    networks:
      - dokploy-network
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${HASH}.rule=Host(`${NGINX_HOST}`)"
      - "traefik.http.services.${HASH}.loadbalancer.server.port=${NGINX_PORT}"

networks:
  dokploy-network:
    external: true

#volumes:
#  ./nginx.conf: {}
#  ./server_cache: {}
